services:
  pgvector:
    image: pgvector/pgvector:pg17-trixie
    restart: always
    ports: 
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - postgres-backup:/backups
volumes:
  postgres-data:
  postgres-backup:

networks:
  default:
    name: database
    external: true
